import OpenAI from 'openai';

export async function analyzeCandidate(position: string, resumeContent: string) {
  if (!process.env.OPENAI_API_KEY) {
    throw new Error('OPENAI_API_KEY is not set');
  }

  const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
  });

  const prompt = `Você é um recrutador sênior e especialista em RH.
Sua tarefa é analisar o currículo a seguir para a vaga de "${position}".
  
Baseando-se no currículo, você deve gerar uma análise em formato JSON com as seguintes chaves estritamente:
- score: Um número inteiro de 0 a 100 avaliando o quão bom é o candidato para a vaga solicitada.
- summary: Um parágrafo curto como resumo profissional destacando pontos fortes ou fracos para a vaga.
- decision: Uma decisão sugerida. Deve ser exatamente uma dessas três palavras: "aprovado", "rejeitado", ou "analisar".

Currículo fornecido:
"""
${resumeContent}
"""
`;

  try {
    const response = await openai.chat.completions.create({
      model: 'gpt-4o-mini',
      messages: [
        { role: 'system', content: 'Você é um bot que apenas gera saída em JSON válido e estruturado.' },
        { role: 'user', content: prompt }
      ],
      response_format: { type: "json_object" }
    });

    const content = response.choices[0].message.content;
    if (!content) throw new Error("No content generated by AI");
    
    const parsed = JSON.parse(content);
    return {
      score: Number(parsed.score),
      summary: String(parsed.summary),
      decision: String(parsed.decision).toLowerCase()
    } as { score: number, summary: string, decision: 'aprovado' | 'rejeitado' | 'analisar' };
  } catch (error) {
    console.error("Error connecting to OpenAI:", error);
    throw error;
  }
}
